### ISSUE TITLE
no nodeJS dependencies?

### ISSUE THREAD

**Issue by pere** [stevage/mapbox-gl-utils#15]
Hi, how could I use these functionalities if I am not running a nodeJS but in just simple plain JS in apache server?
Using rollup.js I have created a bundle.js, but don't know how to implement (if possible) the API on 'standard' JS

Of course this will not work (without nodeJS serving)
const U = require('mapbox-gl-utils').init(map);

Tried several stuff, no success. Thanks in advance

**Comment by stevage** [comment]
So sorry I didn't see this until now. I think you're asking for a plain Javascript distributable that can be included in a Script tag? Sorry, I'm actually not sure how to achieve that.

(I don't think NodeJS has anything to do with this.)

**Comment by pere** [comment]
hi Steve, 
**I think you're asking for a plain Javascript distributable that can be included in a Script tag?**
yes, exactly. I think this is a powerful plugin, and at the end is just JS, so I guess there must be some way to use it on a 'non npm environment' (sorry if I mix concepts, I am not too much into nodejs, npm, etc.)

Please check below the answer I got from stackoverflow. Summarizing it, I managed to create a 'plain JS script', but functions don't work, as they need 'require' methods (if I am not wrong, only available using nodejs)

[(https://stackoverflow.com/questions/62279096/include-js-script-from-a-npm-install)]

thanks in advance

**Comment by stevage** [comment]
Yes, I understand what you need. I can't help you, sorry.
