### ISSUE TITLE
Possibility to use outside node?

### ISSUE THREAD

**Issue by animaux** [stevage/mapbox-gl-utils#27]
Hi Steve,

I was wondering if it was technically possible to build this as frontend extension, like mentioned here: https://stackoverflow.com/questions/62279096/include-js-script-from-a-npm-install

There are some instructions, but the last reply implies there may be some integral problems. However I’m not familiar with node … maybe you could elaborate a bit?

Thanks and all the best!

**Comment by stevage** [comment]
Thanks, yeah I saw that question. I'm definitely happy to support it, I actually just don't know what is required to produce a build in that format.

**Comment by animaux** [comment]
Fair enough, thanks! Anyone we could reach out to? Help! `:)`

**Comment by stevage** [comment]
Ok, I finally figured this out using Rollup. You can use this URL:

https://unpkg.com/mapbox-gl-utils

Demonstration: https://codepen.io/stevebennett/pen/dyNdGNP

**Comment by animaux** [comment]
Brilliant, thanks a lot!
