### ISSUE TITLE
Possible issue with safari <11.1

### ISSUE THREAD

**Issue by distillant** [stevage/mapbox-gl-utils#5]
I was testing our app with safari v11.0.3 desktop, and I think found an error referencing the destructuring operator (...) related to this code , It doesn't effect newer versions of safari, I think the destructing operator was not supported prior to that in safari.
I've never written a node module before, but I was wondering if even though we use  babel/webpack to compile our app, perhaps this requires something additional to instruct npm/yarn to transpile the index.js code as well for older browsers? 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#Browser_compatibility

**Comment by stevage** [comment]
I have run into an issue like this previously as well. Yeah, basically you have to tell your Webpack config to make sure it transpiles this dependency. In that case, with a Vue project, the answer looked like this line in `vue.config.js`'s `configureWebpack` section:

```
    transpileDependencies: ['/node_modules/mapbox-gl-utils/']
```

So I think you can add something very similar to that into your webpack configuration, wherever that is.

Maybe I shouldn't be using ES2015 operators in a library like this, I'm not sure.

**Comment by stevage** [comment]
I've fixed this properly now by including a build process and distributing a babel-transpiled version, as of version 0.28.1.
